version: "3.3"
services:
  proxy:
    ports:
      - "80:80"

  backend:
    ports:
      - "8888:8888"
    volumes:
      - ./backend/app:/app
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    command: /start-reload.sh

  frontend:
    build:
      context: ./frontend
      args:
        FRONTEND_ENV: dev

networks:
  default:
